language: python
python: 2.7

os:
  - linux
  - osx

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35

install: pip install tox

script: tox

matrix:
  allow_failures:
  - { env: "TOXENV=py35", os: "linux" } # Python 3.5 doesn't seem to be available on Travis, but works for me locally
